language: php
php:
  - 7.2

before_script:
  - composer self-update
  - cp .env.example .env
  - php artisan key:generate

script: phpunit

matrix:
  allow_failures:
    - php: 7.2
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always

script:
  - vendor/bin/phpunit